Add product gallery image as fallback for social previews
Yoast/wpseo-woocommerce pull request #669
Opened 2021-03-18 12:23 UTC by JoseeWouters

## Context

* We want to add the product gallery image as last fallback for the social previews, when there are no other images

## Summary

This PR can be summarized in the following changelog entry:

* Adds Product Gallery image as last fallback for the social previews

## Relevant technical choices:

*

## Test instructions

### Test instructions for the acceptance test before the PR gets merged
This PR can be acceptance tested by following these steps:

* Test this together with [Free PR](https://github.com/Yoast/wordpress-seo/pull/16798)
* Add an image to the product gallery, see it's now used in the social preview
* Add a product image, this will now be used in the social preview

### Test instructions for QA when the code is in the RC

* [ ] QA should use the same steps as above.

QA can test this PR by following these steps:

*

## Impact check

This PR affects the following parts of the plugin, which may require extra testing:

*

## UI changes

* [x] This PR changes the UI in the plugin. I have added the 'UI change' label to this PR.

## Documentation

* [ ] I have written documentation for this change.

## Quality assurance

* [x] I have tested this code to the best of my abilities
* [ ] I have added unittests to verify the code works as intended

Fixes [P1-74](https://yoast.atlassian.net/browse/P1-74)

2021-03-22 14:40 UTC, igorschoester requested changes
CR 🏗️

2021-03-22 14:40 UTC, igorschoester commented on js/src/yoastseo-woo-plugin.js
> +			fallbacks.push( fallback );
```suggestion
			fallbacks.push( { productGalleryImage: fallbackImageSrc } );
```

2021-03-22 14:40 UTC, igorschoester commented on js/src/yoastseo-woo-plugin.js
> +			const fallbackImageSrc = fallbackImage.src.replace( /(-150x150)/, "" );
You might want to do that right away when caching the first image?

2021-03-22 14:40 UTC, igorschoester commented on js/src/yoastseo-woo-plugin.js
> +		const dispatch = window.wp.data.dispatch( "yoast-seo/editor" );
Instead of accessing it directly from the window, you should import `dispatch` from `@wordpress/data`.
To make that work (on the same instance) you need to add that package as an external, the same you did with `@wordpress/hooks`.

2021-03-22 14:40 UTC, igorschoester commented on config/webpack/webpack.config.default.js
> +	"@wordpress/hooks",
Nice 🥇

2021-03-30 07:21 UTC, marijnyoast approved these changes
after the changes: CR 👍🏻

2021-04-02 06:58 UTC, maartenleenders commented
@marijnyoast did you also code review the sibling PR in Free?

Acceptance 🚧 
Please expand a bit on the test instructions and the technical decisions, I found it hard to review and test based on the provided information without knowing the context. This will then be difficult for ourselves in the future, and for QA as well.

2021-04-26 08:31 UTC, marijnyoast commented
👍🏻 For the new test instructions. Further Acceptance testing was already done and approved by Maarten.

2021-04-26 08:39 UTC, merged