P1 345 woocommerce snippet in google preview
Yoast/wpseo-woocommerce pull request #670
Opened 2021-03-24 14:54 UTC by marijnyoast

## Context

* We want our Google Preview to reflect how the search result for a product looks in Google. So when the necessary data for Product schema is available, it should show up in the Google Preview.

## Summary

This PR can be summarized in the following changelog entry:

* When used together with the latest version of Wordpress SEO or Wordpress SEO Premium, the Google Preview for products now shows the rating, number of reviews, price and availability like in Google.

## Relevant technical choices:

* For the sake of simplicity we decided to directly dispatch to the WPSEO store.
* Since the needed data is not yet available in WooCommerce's stores, this data is static for now.

## Test instructions

### Test instructions for the acceptance test before the PR gets merged
This PR can be acceptance tested by following these steps:

* Test together with the related branches on Free and the Monorepo, of for QA with the latest RC/Beta of Free/Premium
* Edit a product and save it
* Refresh the page
* Repeat this process with different data added and:
** Verify that when a review has been entered the rating and number of reviews will show up in the Google Preview
** Verify that when a price has been entered the price shows op in the Google Preview
** Verify that when the availability is set or changed it shows up in the Google Preview
* Please check the mobile as well as the desktop view
* Please note that a change is only reflected in the preview after a save and refresh

### Test instructions for QA when the code is in the RC

* [X] QA should use the same steps as above.

QA can test this PR by following these steps:

*

## Impact check

This PR affects the following parts of the plugin, which may require extra testing:

*

## UI changes

* [ ] This PR changes the UI in the plugin. I have added the 'UI change' label to this PR.

## Documentation

* [ ] I have written documentation for this change.

## Quality assurance

* [X] I have tested this code to the best of my abilities
* [ ] I have added unittests to verify the code works as intended

Fixes P1-345

2021-03-31 10:03 UTC, igorschoester requested changes
CR 🏗️

2021-04-01 12:48 UTC, marijnyoast commented on classes/woocommerce-seo.php
> -			add_action( 'init', [ $this, 'initialize_schema' ] );
good spot, it's back!

2021-04-01 12:49 UTC, marijnyoast commented on js/src/yoastseo-woo-plugin.js
> +			dispatch( "yoast-seo/editor" ).setShoppingData( googlePreviewData );
It seems to work without this faulty check indeed

2021-04-07 08:42 UTC, igorschoester reviewed
CR 🏗️

2021-04-07 08:42 UTC, igorschoester commented on js/src/yoastseo-woo-plugin.js
> +		if ( window.wpseoWooL10n.wooGooglePreviewData ) {
I don't think this check is needed. You always add this key to the L10n. The L10n is always there due to the localize_script in PHP.
If you really want, you could add an empty check and then not dispatch if there is no data to add. But looking at what currently is in `wooGooglePreviewData`, this seems to always have something.

2021-04-07 09:01 UTC, igorschoester approved these changes
CR 👍

2021-04-12 08:32 UTC, JoseeWouters commented
Acceptance 👍

2021-04-12 08:35 UTC, merged