918 woocommerce seo php 81 improvements
Yoast/wpseo-woocommerce pull request #927
Opened 2023-07-24 09:05 UTC by vraja-pro

## Context

* Remove `filter_input` usage.

## Summary

This PR can be summarized in the following changelog entry:

* Removes `filter_input` usage for PHP 8.1 improvements.

## Relevant technical choices:

*

## Test instructions

### Test instructions for the acceptance test before the PR gets merged
This PR can be acceptance tested by following these steps:

* Go to `Yoast SEO`->`Woocommerce SEO` 
* Check page looks as expected.
* Inspect page and search in `Elements` tab (or in page source) for `yoast-seo-admin-css-css`
* Check you find it once and a link to a style sheet.

* Go to `Products`, add a product or edit an existing product.
* Go to the woocommerce section in the product and go `Yoast SEO` tab
* Add values to the fields and save.
* Check fields were saved.

### Test instructions for QA when the code is in the RC

* [X] QA should use the same steps as above.

QA can test this PR by following these steps:

*

## Impact check

This PR affects the following parts of the plugin, which may require extra testing:

*

## UI changes

* [ ] This PR changes the UI in the plugin. I have added the 'UI change' label to this PR.

## Documentation

* [ ] I have written documentation for this change.

## Quality assurance

* [X] I have tested this code to the best of my abilities.
* [ ] During testing, I had activated [all plugins that Yoast SEO provides integrations for](https://github.com/Yoast/wordpress-seo/blob/trunk/readme.txt#L106).
* [ ] I have added unit tests to verify the code works as intended.
* [ ] If any part of the code is behind a feature flag, my test instructions also cover cases where the feature flag is switched off.
* [X] I have written this PR in accordance with my team's definition of done.
* [X] I have checked that the base branch is correctly set.

## Innovation

* [X] No innovation project is applicable for this PR.
* [ ] This PR falls under an innovation project. I have attached the `innovation` label.
* [ ] I have added my hours to [the WBSO document](http://yoa.st/wbso).

Fixes #918

2023-08-22 13:42 UTC, igorschoester requested changes
CR 🏗️

2023-08-22 13:42 UTC, igorschoester commented on .gitignore
> +.vscode/
Why not add it to the bunch above the `tmp` section?

2023-08-22 13:42 UTC, igorschoester commented on classes/woocommerce-seo.php
> +		// phpcs:ignore WordPress.Security.NonceVerification.Recommended -- Nonce is not required here.
Maybe mention why not? I.e. because we're purely doing a strict equals check.

2023-08-22 13:42 UTC, igorschoester commented on classes/woocommerce-seo.php
> +		$is_get_wpseo_woo = ( isset( $_GET['page'] ) && is_string( $_GET['page'] ) && $_GET['page'] === 'wpseo_woo' );
And if we're strictly checking, there is no need for the string check 😄 
```suggestion
		$is_get_wpseo_woo = ( isset( $_GET['page'] ) && $_GET['page'] === 'wpseo_woo' );
```

2023-08-22 13:42 UTC, igorschoester commented on classes/woocommerce-yoast-tab.php
> +		$nonce = isset( $_POST['_wpnonce_yoast_seo_woo'] ) ? sanitize_text_field( wp_unslash( $_POST['_wpnonce_yoast_seo_woo'] ) ) : null;
I think due to the`(string)` casting and the `hash_equals` check in `wp_verify_nonce`, the sanitize and possibly the `wp_unslash` is/are not needed.
But we do seem to do the `wp_unslash` a lot in Free. So I'm not entirely sure on that one.

2023-08-22 13:50 UTC, vraja-pro commented on .gitignore
> +.vscode/
Good point!

2023-08-22 13:56 UTC, vraja-pro commented on classes/woocommerce-seo.php
> +		$is_get_wpseo_woo = ( isset( $_GET['page'] ) && is_string( $_GET['page'] ) && $_GET['page'] === 'wpseo_woo' );
Right!

2023-08-23 08:41 UTC, igorschoester approved these changes
CR & AC ✅

2023-08-23 08:41 UTC, merged