438 import global identifier values such as gtin isbn mpn etc into the woocommerce seo plugin fields
Yoast/wpseo-woocommerce pull request #945
Opened 2023-11-07 12:23 UTC by vraja-pro

## Context

* Add export and import columns for wpseo_global_identifier_values (GTIN8, GTIN12 / UPC, GTIN13 / EAN, GTIN14 / ITF-14, ISBN, MPN).

## Summary

This PR can be summarized in the following changelog entry:

* Adds import and export options for global identifier values (GTIN8, GTIN12 / UPC, GTIN13 / EAN, GTIN14 / ITF-14, ISBN, MPN).

## Relevant technical choices:

*

## Test instructions

### Test instructions for the acceptance test before the PR gets merged
This PR can be acceptance tested by following these steps:

### Export functionality
* WooCommerce should be installed.
* Add a product.
* Edit the product, go to the WooCommerce section and click on the Yoast SEO tab
* Add the Product identifiers: GTIN8, GTIN12 / UPC, GTIN13 / EAN, GTIN14 / ITF-14, ISBN, MPN.
* Save
* Go to `Products`->`Export`
* In the export page go to `Which columns should be exported?` and see you can select the Product identifiers.
* Select the ID and Product identifiers: GTIN8, GTIN12 / UPC, GTIN13 / EAN, GTIN14 / ITF-14, ISBN, MPN.
* Export and check the CSV file has the Product identifiers values.

### Import functionality - Update products
* Edit the product that was export and save.
* Go to Products->Import
* Add the file you exported from before and continue.
* Check you want to update products
* Check the mapping is correct
* Import data
* Go back to the product you changed it's Product identifiers values, and see that they were restored.

### Import functionality - Add products
* Delete all products, also from trash.
* Go to Products->Import
* Add the file you exported from before and continue.
* Check the mapping is correct
* Import data
* Go back to products and see the product was imported and has the correct Product identifiers values.

### Test instructions for QA when the code is in the RC

* [X] QA should use the same steps as above.

QA can test this PR by following these steps:

*

## Impact check

This PR affects the following parts of the plugin, which may require extra testing:

*

## UI changes

* [X] This PR changes the UI in the plugin. I have added the 'UI change' label to this PR.

## Documentation

* [ ] I have written documentation for this change.

## Quality assurance

* [X] I have tested this code to the best of my abilities.
* [ ] During testing, I had activated [all plugins that Yoast SEO provides integrations for](https://github.com/Yoast/wordpress-seo/blob/trunk/readme.txt#L106).
* [X] I have added unit tests to verify the code works as intended.
* [ ] If any part of the code is behind a feature flag, my test instructions also cover cases where the feature flag is switched off.
* [X] I have written this PR in accordance with my team's definition of done.
* [X] I have checked that the base branch is correctly set.

## Innovation

* [X] No innovation project is applicable for this PR.
* [ ] This PR falls under an innovation project. I have attached the `innovation` label.
* [ ] I have added my hours to [the WBSO document](http://yoa.st/wbso).

Fixes [Import Global Identifier Values such as GTIN, ISBN, MPN etc into the WooCommerce SEO plugin fields](https://github.com/Yoast/featurerequests/issues/438)

2023-11-08 09:42 UTC, igorschoester requested changes
CR 🏗️

2023-11-08 09:42 UTC, igorschoester commented on classes/woocommerce-import-export.php
> +			update_post_meta( $object->id, 'wpseo_global_identifier_values', $merged );
I'm missing safety here. In the form save we strip all the tags at least.

2023-11-08 09:42 UTC, igorschoester commented on classes/woocommerce-import-export.php
> +	 * This just saves the value in meta data, but you can do anything you want here with the data.
Is this description meaningful here? Seems a bit strange to me (I understand you copied it from their example, I don't think it translates to actual code here is what I'm getting at).

2023-11-08 09:42 UTC, igorschoester commented on classes/woocommerce-import-export.php
> +		return $wpseo_global_identifier_values['gtin8'];
Missing safety in all these export methods: `get_post_meta` can go wrong. Maybe also an opportunity to abstract that to a private method? Using it a lot in this new class.

2023-11-08 09:42 UTC, igorschoester commented on classes/woocommerce-import-export.php
> +	 */
I think you could alter these docs to be specific for each method?

2023-11-08 11:17 UTC, vraja-pro commented on classes/woocommerce-import-export.php
> +
When importing, you have a select fields. This function adds options to that select.

2023-11-08 11:20 UTC, vraja-pro commented on classes/woocommerce-import-export.php
> +	 * This just saves the value in meta data, but you can do anything you want here with the data.
You are right!

2023-11-08 11:24 UTC, vraja-pro commented on classes/woocommerce-import-export.php
> +			$base   = ( $global_identifier_values ) ? $global_identifier_values : $global_identifier_defaults;
Nice!

2023-11-08 11:49 UTC, vraja-pro commented on classes/woocommerce-import-export.php
> +		return $wpseo_global_identifier_values['gtin8'];
I added sanitisation

2023-11-08 13:21 UTC, vraja-pro commented on classes/woocommerce-import-export.php
> +
Done

2023-11-08 13:23 UTC, vraja-pro commented on classes/woocommerce-import-export.php
> +		$columns['gtin8'] = 'gtin8';
This is for different variation of columns names for automatic mapping.

2023-11-08 13:23 UTC, vraja-pro commented on classes/woocommerce-import-export.php
> +		$columns['GTIN12 / UPC'] = 'gtin12';
Added

2023-11-08 13:24 UTC, vraja-pro commented on classes/woocommerce-import-export.php
> +			update_post_meta( $object->id, 'wpseo_global_identifier_values', $merged );
I added sanitisation, I think these method should be public since they are callback methods... Correct me if I'm wrong.

2023-11-09 11:03 UTC, igorschoester requested changes
CR 🏗️

2023-11-09 11:03 UTC, igorschoester commented on classes/woocommerce-import-export.php
> +
The methods are adding the same data to an array though 🤔

2023-11-09 11:11 UTC, vraja-pro commented on classes/woocommerce-import-export.php
> +			update_post_meta( $object->id, 'wpseo_global_identifier_values', $merged );
The return should be one value, so I will adjust your suggestion.

2023-11-09 11:59 UTC, vraja-pro commented on classes/woocommerce-import-export.php
> +	 */
I created a generic method to be applied for all wpseo global identifiers

2023-11-13 11:36 UTC, igorschoester requested changes
CR 🏗️ 

I took the liberty to changing some doc blocks 😇 
Getting very close, but I missed 1 thing in my previous CRs. Plus your refactor is not behaving the same as it was before (the guarantee comment)

2023-11-13 11:36 UTC, igorschoester commented on classes/woocommerce-seo.php
> +		add_action( 'init', [ $this, 'initialize_import_export' ] );
Oh, sorry to only notice this now. However, we probably don't want to initialize this on the frontend, right? I.e. move it inside the `is_admin` if block?

2023-11-13 11:36 UTC, igorschoester commented on classes/woocommerce-import-export.php
> +		}
This does not guarantee that all the values below are represented though, if the DB was messed with. Not sure if that is a problem. If it is a problem, you could merge (again) with the defaults array below?

2023-11-20 10:27 UTC, vraja-pro commented on classes/woocommerce-import-export.php
> +		}
Doesn't hurt 👍🏽

2023-11-20 10:33 UTC, vraja-pro commented on classes/woocommerce-seo.php
> +		add_action( 'init', [ $this, 'initialize_import_export' ] );
I changed the action hook to `admin_init`.

2023-11-21 11:18 UTC, igorschoester approved these changes
CR ✅

2023-11-22 10:17 UTC, enricobattocchi commented
Test ok!

2023-11-22 10:17 UTC, merged