83 add unit tests
Yoast/wpseo-woocommerce pull request #990
Opened 2024-02-01 08:14 UTC by mykola

## Context

* Adds unit tests for `helpers.js`, `woo-identifiers.js`, and `yoastseo-woo-handle-excerpt-editors.js`.

## Summary

This PR can be summarized in the following changelog entry:

* Adds unit tests for `helpers.js`, `woo-identifiers.js`, and `yoastseo-woo-handle-excerpt-editors.js`.

## Relevant technical choices:

* when it's possible structure similar too woocommerce is created, in other case mocks are applied

## Test instructions

### Test instructions for the acceptance test before the PR gets merged
This PR can be acceptance tested by following these steps:

* run ```yarn test```
* make sure that all test are green

#### Relevant test scenarios
* [ ] Changes should be tested with the browser console open
* [ ] Changes should be tested on different posts/pages/taxonomies/custom post types/custom taxonomies
* [ ] Changes should be tested on different editors (Default Block/Gutenberg/Classic/Elementor/other)
* [ ] Changes should be tested on different browsers
* [ ] Changes should be tested on multisite

### Test instructions for QA when the code is in the RC

* [x] QA should use the same steps as above.

QA can test this PR by following these steps:

*

## Impact check

This PR affects the following parts of the plugin, which may require extra testing:

* This is unit tests for existing code so should not impact anything.

## UI changes

* [ ] This PR changes the UI in the plugin. I have added the 'UI change' label to this PR.

## Documentation

* [ ] I have written documentation for this change. For example, comments in the Relevant technical choices, comments in the code, documentation on Confluence / shared Google Drive / [Yoast developer portal](https://developer.yoast.com/), or other.

## Quality assurance

* [x] I have tested this code to the best of my abilities.
* [ ] During testing, I had activated [all plugins that Yoast SEO provides integrations for](https://github.com/Yoast/wordpress-seo/blob/trunk/readme.txt#L106).
* [x] I have added unit tests to verify the code works as intended.
* [ ] If any part of the code is behind a feature flag, my test instructions also cover cases where the feature flag is switched off.
* [x] I have written this PR in accordance with my team's definition of done.
* [x] I have checked that the base branch is correctly set.

## Innovation

* [x] No innovation project is applicable for this PR.
* [ ] This PR falls under an innovation project. I have attached the `innovation` label.
* [ ] I have added my hours to [the WBSO document](http://yoa.st/wbso).

Fixes [#83](https://github.com/Yoast/lingo-other-tasks/issues/83)

2024-02-05 11:23 UTC, FAMarfuaty requested changes
Hey @mykola, good job in adding all these unit tests! 🙌🏽 ✨ 

I have small/minor suggestions mainly on the unit test description :)
Additional note: I guess the Coveralls GH action is complaining now because by adding more unit tests for more files, this PR decreases the coverage? 🤔  Then I assume we can just ignore this?

2024-02-05 11:23 UTC, FAMarfuaty commented on js/tests/initializers/woo-identifiers.test.js
> +import expect from "expect";
```suggestion
```

This import is not necessary since `expect` is Jest's native function.

2024-02-05 11:23 UTC, FAMarfuaty commented on js/tests/initializers/woo-identifiers.test.js
> +	it( "product variations correctly returned", () => {
```suggestion
	it( "should correctly return product variants' data", () => {
```

2024-02-05 11:23 UTC, FAMarfuaty commented on js/tests/initializers/woo-identifiers.test.js
> +	it( "product data correctly returned", () => {
```suggestion
	it( "should correctly return the data of non-variant product", () => {
```

2024-02-05 11:23 UTC, FAMarfuaty commented on js/tests/yoastseo-woo-handle-excerpt-editors.test.js
> +	it( "text editor event handlers are added", () => {
```suggestion
	it( "should add text editor event handlers", () => {
```

2024-02-05 11:23 UTC, FAMarfuaty commented on js/tests/yoastseo-woo-handle-excerpt-editors.test.js
> +	it( "visual editor event handlers are added if tinyMCE is available", () => {
```suggestion
	it( "should add visual editor event handlers when tinyMCE is available", () => {
```

2024-02-05 11:23 UTC, FAMarfuaty commented on js/tests/yoastseo-woo-handle-excerpt-editors.test.js
> +	it( "tinyMCE AddEditor event handlers are added if tinyMCE is loaded", () => {
```suggestion
	it( "should add tinyMCE 'AddEditor' event handlers when tinyMCE is loaded", () => {
```

2024-02-09 11:53 UTC, mhkuu commented
CR/ACC: All comments have been addressed! 👍 Did some more boy scouting. Ready to merge! 🎉

2024-02-09 11:55 UTC, merged